### ISSUE TITLE
Cuda error in func 'cuda_check_cpu_setTarget' at line 41 : invalid device symbol

### ISSUE THREAD

**Issue by rodca1986** [brian112358/nevermore-miner#10]
Hi,

I have a NVIDIA GTX 760 card. The error below is hapenning. 

[2018-03-31 05:09:58] GPU #0: aes_cpu_init invalid device symbol
[2018-03-31 05:09:59] GPU #0: aes_cpu_init invalid device symbol
[2018-03-31 05:10:00] hash order B24BD113607B09EB (5abf4256)
Cuda error in func 'cuda_check_cpu_setTarget' at line 41 : invalid device symbol.

my bat file is ccminer -a x16r -o stratum+tcp://ravenminer.com:3366 -u MYWALLETADDRESS -p c=RVN -i 18 --donate 1 -N 300

It seems to be a configuration error before compiling because the problem does not happen on ccminer-x64-2.2.5-rvn-cuda9 by tpruvot.

I appreciate any help

**Comment by brian112358** [comment]
Unfortunately, Nevermore miner doesn't support GTX 700-series cards, hence your error. Sorry.
