### ISSUE TITLE
Latest version 0.2.2 failing with Illegal Instruction on Ethos. 

### ISSUE THREAD

**Issue by kschroed** [brian112358/nevermore-miner#11]
I updated to the lastest 0.2.2 on my ethos rig which as been running all previous versions just fine.  This one just exits with error:
Illegal Instruction

**Comment by ch0rn** [comment]
Same for me.

**Comment by brian112358** [comment]
Oops. I accidentally set the wrong build flags when building the linux release for v0.2.2. Sorry about that. I've updated the [linux release file](https://github.com/brian112358/nevermore-miner/releases/download/v0.2.2/nevermore-v0.2.2-linux-cuda9.zip). It should work now. Please let me know how it goes.

**Comment by kschroed** [comment]
Looks better thanks.
