### ISSUE TITLE
solo mining blocks always rejected

### ISSUE THREAD

**Issue by ghost** [brian112358/nevermore-miner#15]
![reject reason](https://user-images.githubusercontent.com/38241871/38542965-75e2d5e2-3ccd-11e8-8333-682d644cbbd6.jpg)

Solo mining and keep receiving "bad cb-payee" 
My .conf is:
rpcuser=user
rpcpassword=password
rpcallowip=127.0.0.1
rpcport=3595
server=1
listen=1

my .bat file is
:loop
ccminer -a x16s -o http://127.0.0.1:3595 -u user -p password --coinbase-addr= -i 19
goto loop

The wallet address is valid and coin is EDEN

appreciate it if u could assist

**Comment by sphericale** [comment]
Eden has masternodes so when you create a block you need to include payment to a masternode address, otherwise the block is rejected. I don't think this is supported in the current solo mining code.

**Comment by structdjm** [comment]
I came across two differnt command lines for solo minning rvn, which one should I be using

ccminer -a x16r -o http://127.0.0.1:3333 -u user -p pass --coinbase-addr=WalletAddress -i 19

ccminer  -a x16r -o http://127.0.0.1:3333 -u user -p pass --no-longpoll --no-getwork --no-stratum --coinbase-addr=WalletAddress -i 19

**Comment by repostsc** [comment]
@standard-error what code is added in .bat file for masternode address payee?   
Are you saying you need to have a masternode to solo mine certain coins or that code needs to be added saying the masternode address of the payee 

thank you

**Comment by sphericale** [comment]
There's nothing you can do with a .bat file that will make this work.
It needs changes to the miner source code to handle the masternode payment.

**Comment by repostsc** [comment]
@standard-error thank you for the quick responses. I have been solo mining a ton of little coin with dif lower than 5 and everytime I find a block i get some type of  error from **"does not validate on CPU!" "bad cb-payee"  "rejected reason high hash"** all these are on various forks of ccminer. I've compiled many different ccminer forks myself that claim to fix some of these errors but they either fail to compile or they just throw a different error when a block is found. Is there any information on what one would add to the source code of the miner. Ive tried just about every fork of ccminer thinking of trying a different miner... thank you again

**Comment by swatchie-1** [comment]
yes same issue. bad-cb-payee when mining a coin with hybrid PoW + Masternode. How do we solve it?

**Comment by repostsc** [comment]
@standard-error do you know how a yiimp or nomp pool is able to successfully mine blocks when I connect to there stratum via ccminer but I cant when solo mining? If i set up a pool will i not get these errors?

**Comment by sphericale** [comment]
See the code in https://github.com/tpruvot/yiimp/blob/next/stratum/coinbase.cpp function coinbase_create

You need to either 1. port that code to ccminer or 2. set up your own private yiimp pool and use that

2. is the easier option...

**Comment by swatchie-1** [comment]
@standard-error Hi i tried setting up a Yimp pool but the GPU mining still cannot go through. The error is : Rejected block. If we solo mine, it is bad-cb-payee. Maybe it's not the pool issue?
