### ISSUE TITLE
Add support for SM_71,SM_80, CUDA 10.

### ISSUE THREAD

**Issue by ku4eto** [brian112358/nevermore-miner#28]
As the tittle says, trying to compile with SM_71/80 fails, returns error for non-supported architecture.

Strangely, it accepts SM_70 and SM_72.

Is there ETA for CUDA 10 support implementation?

**Comment by beanjo55** [comment]
if I am not mistaken, sm_70 is Volta (V100, Titan V), sm_72 is not used(maybe for unreleased Turing cards?), and sm_75 is for current Turing cards (RTX 2080, RTX 2080 Ti, RTX 2070)
I dont have cards to test on, but this compiles and should work unless something else changed going to SDK 10
EDIT: read more of the doc, 72 is also for volta, so 70 +72 for Volta, 75 for Turing

**Comment by ku4eto** [comment]
Hm, i was following this article:
http://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/

According to which, Turing is SM_80.  Maybe the source is wrong?

EDIT: Seems like i missed the Nvidia documentation, pertaining the SM_# architecture numbering.

**Comment by beanjo55** [comment]
i found the arch codes in the CUDA release notes for SDK 10
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html

specifically in section 2.1, the line: CUDA 10.0 adds support for the Turing architecture (compute_75 and sm_75).
