### ISSUE TITLE
overclock setting problem

### ISSUE THREAD

**Issue by skyline9394** [brian112358/nevermore-miner#5]
the GPU clock  jumping like crazy  power limit 90% core clock +90 memory +600 
1785 1847 1860 1890 sometime it jump over  1936 1980 and over 2000+ system crash 
can u optimiz it get moer stable 
and can u optimiz the TPD to 98-100 someting like this

**Comment by brian112358** [comment]
Unfortunately, this is the nature of x16r. With the GPU constantly switching between 16 algorithms, there is a high variance in core / memory / power usage for each algorithm. This causes power spikes which can mess up a PSU. I'd recommend setting your TDP around 80% to compensate for this.

From empirical evidence, Nevermore has less power fluctuation than ccminer-2.2.5.
