### ISSUE TITLE
Solo mining

### ISSUE THREAD

**Issue by Mchash** [brian112358/nevermore-miner#9]
hi, thanks the miner works great.
But I cant get the miner to work in solo mining,
Does it support solo mining??

Thanks

**Comment by brian112358** [comment]
The latest release [v0.2](https://github.com/brian112358/nevermore-miner/releases/tag/v0.2) adds support for solo mining from your wallet!

**Comment by ghost** [comment]
I've got solo mining working but with Alps (lyra2z) -- although I haven't hit a coin yet, but it's too early to tell.  Thanks for putting the solo capabilities back into ccminer!
The problem I'm seeing, however, is that it'll run for a minute or so on a new block and then the GPU stops -- core drops to idle.  No errors or messages from the UI.  Next block message and it seems to start right back up.  With multiple GPU's, they seem to stop at different times, but they all eventually cut out from time to time.  It's frequent enough that I'm only effectively mining about 75% of the time.  So, for now I'll run another coin on a pool in parallel.
I should mention this is on a self-compiled version with CUDA 9.1, but shouldn't impact solo feature.
